'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const build = require('../lib/build.js');
const users = require('../lib/users.js');
const { METRICS } = require('../lib/jazco.js');

const usersSeries = (to, est = () => false) => {
  const out = [];
  let n = 100;
  for (let d = '2022-11-17'; d <= to; d = users.addDays(d, 1)) {
    n += 10;
    out.push({ date: d, users: n, users_est: est(d), users_src: est(d) ? 'interp' : 'commons' });
  }
  return out;
};
const act = (date, v = {}) => ({ date, likers: 1000, posters: 600, followers: 300, blockers: 60, posts: 3000, likes: 20000, follows: 1500, blocks: 300, ...v });
const actRange = (from, to, fn = () => ({})) => {
  const out = [];
  for (let d = from; d <= to; d = users.addDays(d, 1)) out.push(act(d, fn(d)));
  return out;
};

test('mergeActivity: the API wins for dates it returns, the archive keeps the rest', () => {
  const archive = [
    { date: '2023-02-28', likers: null, posters: null },
    { ...act('2023-03-01', { likers: 1 }), users: 5, flags: ['likers'], dau: 9 },
    { ...act('2023-03-02', { likers: 2 }) },
  ];
  const api = [act('2023-03-02', { likers: 222 }), act('2023-03-03', { likers: 333 })];
  const merged = build.mergeActivity(api, archive);
  assert.deepEqual(merged.map((r) => [r.date, r.likers]), [['2023-03-01', 1], ['2023-03-02', 222], ['2023-03-03', 333]]);
  assert.deepEqual(Object.keys(merged[0]), ['date', ...METRICS], 'only raw activity values survive the merge');
});

test('assembleDays: contiguous rows from 2022-11-17, velocity, est propagation, activity and dau', () => {
  const series = usersSeries('2023-03-10', (d) => d === '2023-03-05');
  const activity = actRange('2023-03-01', '2023-03-09', (d) => (d === '2023-03-04' ? { likers: 5, likes: 10 } : {}));
  const days = build.assembleDays({ users: series, activity, lastCompleteDay: '2023-03-10' });
  assert.equal(days[0].date, '2022-11-17');
  assert.equal(days.at(-1).date, '2023-03-10');
  assert.equal(days.length, 114);
  for (const d of days) assert.deepEqual(Object.keys(d), build.ROW_KEYS);
  assert.equal(days[0].new_users, null);
  assert.equal(days[0].new_users_est, false);
  assert.equal(days[1].new_users, 10);
  const byDate = Object.fromEntries(days.map((d) => [d.date, d]));
  assert.equal(byDate['2023-03-05'].new_users_est, true);
  assert.equal(byDate['2023-03-06'].new_users_est, true, 'the day after an estimated day is estimated too');
  assert.equal(byDate['2023-03-07'].new_users_est, false);
  assert.equal(byDate['2023-02-28'].likers, null);
  assert.equal(byDate['2023-02-28'].dau, null);
  assert.equal(byDate['2023-03-01'].dau, 1000);
  assert.equal(byDate['2023-03-10'].posters, null, 'no activity row yet: nulls, not zeros');
  assert.deepEqual(byDate['2023-03-10'].flags, []);
  assert.ok(build.validateDataset(build.buildDataset({ generatedAt: '2023-03-11T03:00:00.000Z', snapshot: { total_users: 1 }, days })));
});

test('assembleDays flags outages on the merged history and nulls dau for them', () => {
  const series = usersSeries('2024-09-10');
  const activity = actRange('2024-07-01', '2024-09-10');
  const days = build.assembleDays({ users: series, activity, lastCompleteDay: '2024-09-10' });
  const d = days.find((r) => r.date === '2024-09-02');
  assert.deepEqual(d.flags, METRICS);
  assert.equal(d.dau, null);
  assert.equal(d.posters, 600, 'raw value kept even when flagged');
});

test('assembleDays ignores activity after the last complete day and fails on a users gap', () => {
  const days = build.assembleDays({ users: usersSeries('2023-03-02'), activity: actRange('2023-03-01', '2023-03-05'), lastCompleteDay: '2023-03-02' });
  assert.equal(days.at(-1).date, '2023-03-02');
  const holey = usersSeries('2023-03-02').filter((u) => u.date !== '2023-01-01');
  assert.throws(() => build.assembleDays({ users: holey, activity: [], lastCompleteDay: '2023-03-02' }), /no users value for 2023-01-01/);
});

test('data file and CSV round-trip', () => {
  const days = build.assembleDays({ users: usersSeries('2024-09-03', (d) => d === '2024-09-01'), activity: actRange('2024-08-20', '2024-09-03'), lastCompleteDay: '2024-09-03' });
  const snapshot = { total_users: 210, updated_at: '2023-03-06T03:00:00Z', total_posts: 1, total_likes: 2, total_follows: 3, source: 'bsky-search.jazco.io/stats' };
  const data = build.buildDataset({ generatedAt: '2023-03-06T03:10:00.000Z', snapshot, days });
  const js = build.serializeDataJs(data);
  assert.ok(js.startsWith('// generated by updateData.js — do not edit\nwindow.BLUESKY_DATA = {"schema":1,"generated_at":'));
  assert.equal(js.split('\n').length, days.length + 4, 'one row per line');
  assert.deepEqual(build.parseDataJs(js), data);
  // the file runs as a classic script and defines the global
  const sandbox = {};
  new Function('window', js)(sandbox);
  assert.deepEqual(sandbox.BLUESKY_DATA, data);

  const csv = build.serializeCsv(data);
  const lines = csv.trimEnd().split('\n');
  assert.equal(lines[0], 'date,users,users_estimated,users_source,new_users,dau,posters,likers,followers,blockers,posts,likes,follows,blocks,flags');
  assert.equal(lines.length, days.length + 1);
  assert.equal(lines[1], '2022-11-17,110,false,commons,,,,,,,,,,,');
  const parsed = build.parseCsv(csv);
  parsed.forEach((p, i) => {
    const d = days[i];
    assert.equal(p.date, d.date);
    assert.equal(p.users, d.users);
    assert.equal(p.users_estimated, d.users_est);
    assert.equal(p.users_source, d.users_src);
    for (const k of ['new_users', 'dau', ...METRICS]) assert.equal(p[k], d[k], `${d.date} ${k}`);
    assert.deepEqual(p.flags, d.flags);
  });
  assert.equal(lines.at(-3), '2024-09-01,6650,true,interp,10,,600,1000,300,60,3000,20000,1500,300,likers|posters|followers|blockers|posts|likes|follows|blocks');
  assert.equal(lines.find((l) => l.startsWith('2024-08-30,')), '2024-08-30,6630,false,commons,10,1000,600,1000,300,60,3000,20000,1500,300,');
});

test('parseDataJs reads the provisional file format and rejects other files', () => {
  const provisional = '// PROVISIONAL fixture\nwindow.BLUESKY_DATA = {"schema":1,"provisional":true,"days":[\n{"date":"2022-11-17"}\n]};\n';
  assert.deepEqual(build.parseDataJs(provisional).days, [{ date: '2022-11-17' }]);
  assert.throws(() => build.parseDataJs('const x = 1;'), /not found/);
  assert.throws(() => build.parseDataJs('window.BLUESKY_DATA = {}'), /semicolon/);
});

test('validateDataset catches gaps, missing keys and bad velocity', () => {
  const days = build.assembleDays({ users: usersSeries('2022-11-20'), activity: [], lastCompleteDay: '2022-11-20' });
  const ok = build.buildDataset({ generatedAt: 'x', snapshot: { total_users: 1 }, days });
  assert.ok(build.validateDataset(ok));
  assert.throws(() => build.validateDataset({ ...ok, days: [days[0], days[2], days[3]] }), /not contiguous/);
  assert.throws(() => build.validateDataset({ ...ok, days: days.map((d, i) => (i === 2 ? { ...d, new_users: 0 } : d)) }), /new_users/);
  const { dau, ...noDau } = days[1];
  assert.throws(() => build.validateDataset({ ...ok, days: [days[0], noDau, ...days.slice(2)] }), /keys/);
  assert.throws(() => build.validateDataset({ ...ok, days: days.map((d) => ({ ...d, users_src: 'guess' })) }), /users_src/);
});

test('the committed data file matches the contract', { skip: !fs.existsSync(path.join(__dirname, '..', 'data', 'bluesky-data.js')) }, () => {
  const data = build.parseDataJs(fs.readFileSync(path.join(__dirname, '..', 'data', 'bluesky-data.js'), 'utf8'));
  assert.ok(build.validateDataset(data));
  assert.equal(data.activity_start, '2023-03-01');
  assert.equal(data.collection_start, '2023-05-01');
  assert.deepEqual(data.live_source, build.LIVE_SOURCE);
  // updateData.js falls back to the hourly bot (or an archived reading) when Jaz's total is stale.
  assert.match(data.snapshot.source, /^(bsky-search\.jazco\.io\/stats|hourlybskyusers\.bsky\.social \(relays bsky-search\.jazco\.io\/stats\)|\w+ archive)$/);
});
