'use strict';
// Assembles the published dataset (data/bluesky-data.js + data/bluesky-daily.csv). Pure functions.

const { METRICS, ACTIVITY_START, COLLECTION_START, flagActivity, computeDau } = require('./jazco.js');
const { SERIES_START, addDays } = require('./users.js');
const { netDaily } = require('./accounts.js');

const SCHEMA = 1;
const LIVE_SOURCE = {
  type: 'bsky-author-feed',
  actor: 'did:plc:5he4nkza7eqhmirg3azchqy6',
  pattern: 'Total Bluesky users: ([\\d,]+)',
};
const ROW_KEYS = [
  'date', 'users', 'users_est', 'users_src', 'new_users', 'new_users_est',
  'likers', 'posters', 'followers', 'blockers', 'posts', 'likes', 'follows', 'blocks', 'dau', 'flags',
];
const USERS_SOURCES = ['commons', 'wayback', 'bot', 'elaval', 'krekeny', 'jazco', 'plc-shaped', 'interp'];
const CSV_COLUMNS = [
  'date', 'users', 'users_estimated', 'users_source', 'new_users', 'dau',
  'posters', 'likers', 'followers', 'blockers', 'posts', 'likes', 'follows', 'blocks', 'flags',
];
const JS_HEADER = '// generated by updateData.js — do not edit\n';
const JS_PREFIX = 'window.BLUESKY_DATA = ';

// Activity rows keyed by date. The API wins for every date it returns (Jaz revises history,
// e.g. the April 2026 repair); the archive keeps dates the API no longer returns.
function mergeActivity(apiRows, archiveDays = []) {
  const byDate = new Map();
  for (const d of archiveDays) {
    if (!d || d.date < ACTIVITY_START || METRICS.every((m) => d[m] === null || d[m] === undefined)) continue;
    byDate.set(d.date, Object.fromEntries([['date', d.date], ...METRICS.map((m) => [m, d[m] ?? null])]));
  }
  for (const r of apiRows) byDate.set(r.date, Object.fromEntries([['date', r.date], ...METRICS.map((m) => [m, r[m]])]));
  return [...byDate.values()].sort((a, b) => (a.date < b.date ? -1 : 1));
}

// users: [{date, users, users_est, users_src}] covering SERIES_START..lastCompleteDay.
// activity: merged raw activity rows (flags are computed here, on the whole history).
function assembleDays({ users, activity, lastCompleteDay }) {
  const usersByDate = new Map(users.map((u) => [u.date, u]));
  const flagged = new Map(flagActivity(activity.filter((r) => r.date <= lastCompleteDay)).map((r) => [r.date, r]));
  const days = [];
  let prev = null;
  for (let date = SERIES_START; date <= lastCompleteDay; date = addDays(date, 1)) {
    const u = usersByDate.get(date);
    if (!u || !Number.isSafeInteger(u.users)) throw new Error(`no users value for ${date}`);
    const a = flagged.get(date);
    const row = {
      date,
      users: u.users,
      users_est: Boolean(u.users_est),
      users_src: u.users_src,
      new_users: prev ? u.users - prev.users : null,
      new_users_est: prev ? Boolean(u.users_est || prev.users_est) : false,
    };
    for (const m of METRICS) row[m] = a ? a[m] : null;
    row.dau = a ? computeDau(a) : null;
    row.flags = a ? a.flags : [];
    days.push(row);
    prev = row;
  }
  return days;
}

const OWN_COUNT_KEYS = ['date', 'finished_at', 'complete', 'repos', 'active', 'deactivated', 'takendown', 'suspended', 'deleted', 'other'];

// Our own listRepos count (data/accounts-daily.json): every run, plus net change between complete runs.
function buildOwnCount(rows) {
  if (!rows || !rows.length) return null;
  return {
    source: 'com.atproto.sync.listRepos on Bluesky-operated PDS hosts',
    rows: rows.map((r) => Object.fromEntries(OWN_COUNT_KEYS.map((k) => [k, r[k]]))),
    net: netDaily(rows),
  };
}

function buildDataset({ generatedAt, snapshot, days, ownCountRows = null }) {
  return {
    schema: SCHEMA,
    generated_at: generatedAt,
    last_complete_day: days[days.length - 1].date,
    snapshot,
    live_source: LIVE_SOURCE,
    activity_start: ACTIVITY_START,
    collection_start: COLLECTION_START,
    own_count: buildOwnCount(ownCountRows),
    days,
  };
}

// Throws on anything a consumer relies on: contiguous days, every key present, sane types.
function validateDataset(data) {
  const problems = [];
  if (data.schema !== SCHEMA) problems.push('schema');
  if (!data.snapshot || !Number.isSafeInteger(data.snapshot.total_users)) problems.push('snapshot.total_users');
  const days = data.days || [];
  if (!days.length) problems.push('no days');
  if (days.length && days[0].date !== SERIES_START) problems.push(`first day ${days[0].date}`);
  if (days.length && data.last_complete_day !== days[days.length - 1].date) problems.push('last_complete_day');
  days.forEach((d, i) => {
    const keys = Object.keys(d);
    if (keys.length !== ROW_KEYS.length || ROW_KEYS.some((k, j) => keys[j] !== k)) problems.push(`${d.date}: keys`);
    if (i && addDays(days[i - 1].date, 1) !== d.date) problems.push(`${d.date}: not contiguous`);
    if (!Number.isSafeInteger(d.users) || d.users <= 0) problems.push(`${d.date}: users`);
    if (!USERS_SOURCES.includes(d.users_src)) problems.push(`${d.date}: users_src ${d.users_src}`);
    if (i && d.new_users !== d.users - days[i - 1].users) problems.push(`${d.date}: new_users`);
    if (!Array.isArray(d.flags) || d.flags.some((f) => !METRICS.includes(f))) problems.push(`${d.date}: flags`);
    if (d.date < ACTIVITY_START && (d.dau !== null || METRICS.some((m) => d[m] !== null))) problems.push(`${d.date}: activity before start`);
  });
  if (data.own_count !== null && data.own_count !== undefined) {
    const oc = data.own_count;
    if (!Array.isArray(oc.rows) || !Array.isArray(oc.net)) problems.push('own_count shape');
    else if (oc.rows.some((r) => !Number.isSafeInteger(r.active) || !/^\d{4}-\d{2}-\d{2}$/.test(r.date))) problems.push('own_count rows');
  }
  if (problems.length) throw new Error('invalid dataset: ' + problems.slice(0, 10).join('; ') + (problems.length > 10 ? ` (+${problems.length - 10} more)` : ''));
  return true;
}

function serializeDataJs(data) {
  const { days, ...head } = data;
  const top = JSON.stringify(head);
  return JS_HEADER + JS_PREFIX + top.slice(0, -1) + ',"days":[\n' + days.map((d) => JSON.stringify(d)).join(',\n') + '\n]};\n';
}

function parseDataJs(text) {
  const start = text.indexOf(JS_PREFIX);
  if (start === -1) throw new Error('data file: window.BLUESKY_DATA assignment not found');
  const body = text.slice(start + JS_PREFIX.length).trimEnd();
  if (!body.endsWith(';')) throw new Error('data file: missing trailing semicolon');
  return JSON.parse(body.slice(0, -1));
}

const csvCell = (v) => (v === null || v === undefined ? '' : String(v));

function serializeCsv(data) {
  const lines = [CSV_COLUMNS.join(',')];
  for (const d of data.days) {
    lines.push([
      d.date, d.users, d.users_est, d.users_src, d.new_users, d.dau,
      d.posters, d.likers, d.followers, d.blockers, d.posts, d.likes, d.follows, d.blocks, d.flags.join('|'),
    ].map(csvCell).join(','));
  }
  return lines.join('\n') + '\n';
}

function parseCsv(text) {
  const [header, ...rows] = text.trimEnd().split('\n');
  const cols = header.split(',');
  const num = (s) => (s === '' ? null : Number(s));
  return rows.map((line) => {
    const cells = line.split(',');
    const o = Object.fromEntries(cols.map((c, i) => [c, cells[i]]));
    const out = { date: o.date, users: num(o.users), users_estimated: o.users_estimated === 'true', users_source: o.users_source };
    for (const c of cols.slice(4, -1)) out[c] = num(o[c]);
    out.flags = o.flags ? o.flags.split('|') : [];
    return out;
  });
}

module.exports = {
  buildOwnCount,
  SCHEMA,
  LIVE_SOURCE,
  ROW_KEYS,
  USERS_SOURCES,
  CSV_COLUMNS,
  mergeActivity,
  assembleDays,
  buildDataset,
  validateDataset,
  serializeDataJs,
  parseDataJs,
  serializeCsv,
  parseCsv,
};
